/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpassignment;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReservationInfo extends javax.swing.JFrame {

    public ReservationInfo() {
        initComponents();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCustName = new javax.swing.JTextField();
        jTextFieldCustID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCustEmail = new javax.swing.JTextField();
        jTextFieldCustCNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnShow2 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        btnUpdateTxT = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbRID = new javax.swing.JComboBox<String>();
        txtAvailable = new javax.swing.JTextField();
        cbRID1 = new javax.swing.JComboBox<String>();
        btnClear3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Room ID");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Customer IC/Passport");

        jTextFieldCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustIDActionPerformed(evt);
            }
        });
        jTextFieldCustID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCustIDKeyTyped(evt);
            }
        });

        jLabel4.setText("Customer Email");

        jLabel5.setText("Contact Number");

        jTextFieldCustCNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustCNumActionPerformed(evt);
            }
        });
        jTextFieldCustCNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCustCNumKeyTyped(evt);
            }
        });

        jLabel6.setText("CheckIn");

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 0, 48)); // NOI18N
        jLabel7.setText("Room Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName("jLabelRoomInfo");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RoomID", "Name", "IC", "Email", "ContactNo", "CheckIn", "CheckOut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setText("CheckOut");

        btnShow2.setText("Show");
        btnShow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShow2ActionPerformed(evt);
            }
        });

        btnClear2.setText("Clear");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });

        btnUpdateTxT.setText("Update");
        btnUpdateTxT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTxTActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbRID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Room", "R10", "R11", "R12", "R13", "R14", "R15", "R16", "R17", "R18", "R19", "R20", "R21", "R22", "R23", "R24", "R25", "R26", "R27", "R28", "R29" }));

        cbRID1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Room", "R10", "R11", "R12", "R13", "R14", "R15", "R16", "R17", "R18", "R19", "R20", "R21", "R22", "R23", "R24", "R25", "R26", "R27", "R28", "R29" }));

        btnClear3.setText("Clear");
        btnClear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldCustCNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCustEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCustID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCustName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbRID, javax.swing.GroupLayout.Alignment.LEADING, 0, 172, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbRID1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnClear3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btnBack)
                                        .addGap(145, 145, 145)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnUpdateTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(76, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear3))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCustCNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)
                                .addContainerGap(26, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateTxT)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear2)
                        .addComponent(btnShow2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabelRoomID");
        jLabel1.getAccessibleContext().setAccessibleDescription("");
        jLabel2.getAccessibleContext().setAccessibleName("jLabelCustN");
        jLabel3.getAccessibleContext().setAccessibleName("jLabelCustID");
        jTextFieldCustName.getAccessibleContext().setAccessibleName("jTextFieldCustN");
        jTextFieldCustID.getAccessibleContext().setAccessibleName("jTextFieldCID");
        jTextFieldCustID.getAccessibleContext().setAccessibleDescription("");
        jLabel4.getAccessibleContext().setAccessibleName("jLabelEmail");
        jLabel5.getAccessibleContext().setAccessibleName("jLabelContactN");
        jTextFieldCustEmail.getAccessibleContext().setAccessibleName("jTextFieldEmail");
        jTextFieldCustCNum.getAccessibleContext().setAccessibleName("jTextFieldContactN");
        jLabel6.getAccessibleContext().setAccessibleName("jLabelDOS");
        btnAdd.getAccessibleContext().setAccessibleName("jButtonAdd");
        btnUpdate.getAccessibleContext().setAccessibleName("jButtonUpdate");
        btnDel.getAccessibleContext().setAccessibleName("jButtonDelete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        String filePath = "ReservationInfo.txt";
        File Rslist = new File(filePath);
        Scanner scan ;
        try {
            scan = new Scanner(Rslist); 
            int rinfo=0;
            Object RRoom=cbRID1.getSelectedItem();
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dFormat.format(dcCheck.getDate()) ;
            while (scan.hasNextLine())
            {
            String line = scan.nextLine();
            if (!(line.isEmpty()))
            {
            
            String room=line.split(";")[0];
            String datein=line.split(";")[5];
            String dateout=line.split(";")[6];
            
            if(RRoom.equals(room) && (date.compareTo(datein)>=0 && date.compareTo(dateout)<=0)){
                rinfo=1;

            }
            if(rinfo==1 && rinfo!=0){
                txtAvailable.setText("Not Available");

            }
            else{
                txtAvailable.setText("Available");
            }
            }
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Please select date and room!");
        }
        
            
            
        
            
            
           

        
    
        
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String filePath = "ReservationInfo.txt";
        File Rslist = new File(filePath);
        Scanner scan;
        
        try {
            scan = new Scanner(Rslist); 
            int rinfo=0;
        

            Object RRoom=cbRID.getSelectedItem();
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String CheckIn = dFormat.format(dcCheckIn.getDate()) ;
            String CheckOut = dFormat.format(dcCheckOut.getDate()) ;
           
            while (scan.hasNextLine())
            {
            String line = scan.nextLine();
            if (!(line.isEmpty()))
            {
            
            String room=line.split(";")[0];
            String datein=line.split(";")[5];
            String dateout=line.split(";")[6];
            
            
            if(RRoom.equals(room) &&((CheckIn.compareTo(datein)>=0 && CheckIn.compareTo(dateout)<=0) || (CheckOut.compareTo(datein)>=0 && CheckOut.compareTo(dateout)<=0))){
                rinfo=1;
                
            }
            if(rinfo==1 && rinfo!=0){
                JOptionPane.showMessageDialog(null,"This room is already reserved!");
                break;
            
            }
            else if (CheckOut.compareTo(CheckIn)<=0 ){
                JOptionPane.showMessageDialog(null,"CheckOut Date must greater than CheckIn Date");
                break;
            }
            else{
                DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
                tableModel.addRow(new Object[]{cbRID.getSelectedItem(),jTextFieldCustName.getText(),jTextFieldCustID.getText(),jTextFieldCustEmail.getText(),jTextFieldCustCNum.getText(),CheckIn,CheckOut});
            }
            }
            }
            
            
   
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,"Please insert all data!");
        } 
        
    
    
    
    
    

        
         
         
    }//GEN-LAST:event_btnAddActionPerformed

    

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        
        try{
            int SelectedRowIndex = jTable2.getSelectedRow();
        tableModel.removeRow(SelectedRowIndex);
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Please Select Data to delete!");
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cbRID.setSelectedIndex(0);
        jTextFieldCustName.setText("");
        jTextFieldCustID.setText("");
        jTextFieldCustEmail.setText("");
        jTextFieldCustCNum.setText("");
        dcCheckIn.setDate(null);
        dcCheckOut.setDate(null);
        
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
       
        
           
        try {
            int selectedRow = jTable2.getSelectedRow();
            DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
            cbRID.setSelectedItem(tableModel.getValueAt(selectedRow, 0).toString());
            jTextFieldCustName.setText(tableModel.getValueAt(selectedRow, 1).toString());
            jTextFieldCustID.setText(tableModel.getValueAt(selectedRow, 2).toString());
            jTextFieldCustEmail.setText(tableModel.getValueAt(selectedRow, 3).toString());
            jTextFieldCustCNum.setText(tableModel.getValueAt(selectedRow, 4).toString());
            Date datein = new SimpleDateFormat("yyyy-MM-dd").parse((String)tableModel.getValueAt(selectedRow, 5));
            dcCheckIn.setDate(datein);
            Date dateout = new SimpleDateFormat("yyyy-MM-dd").parse((String)tableModel.getValueAt(selectedRow, 6));
            dcCheckOut.setDate(dateout);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(ReservationInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        
        }
        
        
        

    }//GEN-LAST:event_jTable2MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        try{
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String CheckIn = dFormat.format(dcCheckIn.getDate()) ;
        String CheckOut = dFormat.format(dcCheckOut.getDate()) ;
       
        int i = jTable2.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        if(i>=0)
        {
            tableModel.setValueAt(cbRID.getSelectedItem(),i,0);
            tableModel.setValueAt(jTextFieldCustName.getText(),i,1);
            tableModel.setValueAt(jTextFieldCustID.getText(),i,2);
            tableModel.setValueAt(jTextFieldCustEmail.getText(),i,3);
            tableModel.setValueAt(jTextFieldCustCNum.getText(),i,4);
            tableModel.setValueAt(CheckIn, i, 5);
            tableModel.setValueAt(CheckOut, i, 6);
            
           
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }
        }catch(Exception Ex){
            JOptionPane.showMessageDialog(null,"Please select data and make sure all fields are inserted!");
        }
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnShow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShow2ActionPerformed
        String filePath = "ReservationInfo.txt";
        File Rslist = new File(filePath);
        
         try{
            BufferedReader br = new BufferedReader(new FileReader(Rslist));
            
            
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            

            // get lines from txt file
            Object[] tableLines = br.lines.toArray();

            // extratct data from lines
            // set data to jtable model
            for (Object tableLine : tableLines) {
                String line = tableLine.toString().trim();
                String[] dataRow = line.split(";");
                model.addRow(dataRow);
            }


        }catch (IOException ex){
           

        }
    
        
         
    }//GEN-LAST:event_btnShow2ActionPerformed

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void btnUpdateTxTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTxTActionPerformed
        String filePath = "ReservationInfo.txt";
        File file = new File(filePath);
       
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < jTable2.getRowCount(); i++){//rows
                for(int j = 0; j < jTable2.getColumnCount(); j++){//columns
                    bw.write(jTable2.getValueAt(i, j).toString()+";");
                    
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
            JOptionPane.showMessageDialog(null,"Update Successfully");
            
            
            
            
            
            
       
            
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_btnUpdateTxTActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jTextFieldCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustIDActionPerformed
       
    }//GEN-LAST:event_jTextFieldCustIDActionPerformed

    private void jTextFieldCustIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustIDKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)
               || c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCustIDKeyTyped

    private void jTextFieldCustCNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustCNumActionPerformed
        
    }//GEN-LAST:event_jTextFieldCustCNumActionPerformed

    private void jTextFieldCustCNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustCNumKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)
              ||  c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCustCNumKeyTyped

    private void btnClear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3ActionPerformed
        cbRID1.setSelectedIndex(0);
        dcCheck.setDate(null);
        txtAvailable.setText("");
    }//GEN-LAST:event_btnClear3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReservationInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShow2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateTxT;
    private javax.swing.JComboBox<String> cbRID;
    private javax.swing.JComboBox<String> cbRID1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldCustCNum;
    private javax.swing.JTextField jTextFieldCustEmail;
    private javax.swing.JTextField jTextFieldCustID;
    private javax.swing.JTextField jTextFieldCustName;
    private javax.swing.JTextField txtAvailable;
    // End of variables declaration//GEN-END:variables
}
